server:
  port: 8094
  
spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/account
      
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
