server:
  port: 8091
  
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product
      
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
