server:
  port: 8093
  
spring:
  application:
    name: transaction-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/transaction
      
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
